image: android

workflows:
  build_android:
    name: Tests + APKs
    max_build_duration: 45
    scripts:
      - name: Check toolchain
        script: |
          java -version
          ./gradlew --version
      - name: Run unit tests
        script: |
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8"
          ./gradlew --no-daemon testDebugUnitTest
      - name: Build debug APK
        script: |
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8"
          ./gradlew --no-daemon assembleDebug
      - name: Build release APK
        script: |
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8"
          ./gradlew --no-daemon assembleRelease
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/apk/release/*.apk
      - app/build/reports/tests/**/*.html